import { Doctor, Appointment, PredictionHistory, AuditLog } from './types';

export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'doc-1',
    name: 'Dr. Sarah Jenkins',
    specialty: 'Senior Cardiologist',
    department: 'Cardiology',
    experience: 16,
    rating: 4.9,
    availability: ['Monday', 'Wednesday', 'Friday'],
    email: 'sarah.jenkins@hospital.ai',
    phone: '+1 (555) 234-5678',
    status: 'Active',
    imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=300',
  },
  {
    id: 'doc-2',
    name: 'Dr. Michael Chang',
    specialty: 'Neurologist & Brain Specialist',
    department: 'Neurology',
    experience: 12,
    rating: 4.8,
    availability: ['Tuesday', 'Thursday'],
    email: 'michael.chang@hospital.ai',
    phone: '+1 (555) 345-6789',
    status: 'Active',
    imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=300',
  },
  {
    id: 'doc-3',
    name: 'Dr. Alisha Patel',
    specialty: 'Pulmonologist',
    department: 'Pulmonology & Respiratory Care',
    experience: 9,
    rating: 4.7,
    availability: ['Monday', 'Tuesday', 'Wednesday'],
    email: 'alisha.patel@hospital.ai',
    phone: '+1 (555) 456-7890',
    status: 'Active',
    imageUrl: 'https://images.unsplash.com/photo-1594824813573-246434de83fb?auto=format&fit=crop&q=80&w=300',
  },
  {
    id: 'doc-4',
    name: 'Dr. Robert Vance',
    specialty: 'Urologist & Kidney Transplant Specialist',
    department: 'Urology & Nephrology',
    experience: 20,
    rating: 4.95,
    availability: ['Wednesday', 'Thursday', 'Friday'],
    email: 'robert.vance@hospital.ai',
    phone: '+1 (555) 567-8901',
    status: 'Active',
    imageUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=300',
  },
  {
    id: 'doc-5',
    name: 'Dr. Elena Rostova',
    specialty: 'Oncologist & Cancer Researcher',
    department: 'Oncology',
    experience: 14,
    rating: 4.85,
    availability: ['Monday', 'Thursday'],
    email: 'elena.rostova@hospital.ai',
    phone: '+1 (555) 678-9012',
    status: 'On Leave',
    imageUrl: 'https://images.unsplash.com/photo-1527613426441-4da17471b66d?auto=format&fit=crop&q=80&w=300',
  },
  {
    id: 'doc-6',
    name: 'Dr. James Mercer',
    specialty: 'Radiologist',
    department: 'Radiology',
    experience: 11,
    rating: 4.6,
    availability: ['Tuesday', 'Thursday', 'Friday'],
    email: 'james.mercer@hospital.ai',
    phone: '+1 (555) 789-0123',
    status: 'Active',
    imageUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=300',
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-1',
    doctorId: 'doc-1',
    doctorName: 'Dr. Sarah Jenkins',
    specialty: 'Senior Cardiologist',
    patientName: 'John Doe',
    patientAge: 45,
    date: '2026-06-26',
    time: '10:00 AM',
    status: 'Confirmed',
    symptoms: 'Mild chest tightness during heavy aerobic activity and fatigue.',
    severity: 'Medium',
  },
  {
    id: 'apt-2',
    doctorId: 'doc-3',
    doctorName: 'Dr. Alisha Patel',
    specialty: 'Pulmonologist',
    patientName: 'Emily Watson',
    patientAge: 32,
    date: '2026-06-27',
    time: '02:30 PM',
    status: 'Pending',
    symptoms: 'Persistent dry cough following a viral fever, slight wheezing.',
    severity: 'Low',
  },
  {
    id: 'apt-3',
    doctorId: 'doc-2',
    doctorName: 'Dr. Michael Chang',
    specialty: 'Neurologist & Brain Specialist',
    patientName: 'George Miller',
    patientAge: 58,
    date: '2026-06-28',
    time: '09:15 AM',
    status: 'Confirmed',
    symptoms: 'Frequent migraine episodes accompanied by momentary blurred vision.',
    severity: 'High',
  },
];

export const INITIAL_PREDICTIONS: PredictionHistory[] = [
  {
    id: 'pred-1',
    patientName: 'John Doe',
    patientAge: 45,
    diseaseType: 'Heart Disease',
    confidence: 88,
    severity: 'Mild',
    date: '2026-06-24',
    suggestedSpecialist: 'Cardiology (Dr. Sarah Jenkins)',
    symptomsOrMetrics: {
      'Blood Pressure': '138 mmHg',
      'Cholesterol': '242 mg/dL',
      'Max Heart Rate': '155 bpm',
      'Chest Pain Type': 'Atypical Angina',
      'ECG Result': 'ST-T Wave Abnormality',
    },
    diagnosisText: 'The clinical metrics suggest moderate cardiovascular risk. Blood pressure and cholesterol parameters indicate mild plaque buildup. Immediate lifestyle adjustments and clinical correlation are advised.',
    recommendations: [
      'Initiate daily cardiovascular monitoring and check bp twice a week.',
      'Adopt a low-sodium, heart-healthy Mediterranean diet.',
      'Schedule a physical stress test with a cardiologist.',
      'Maintain a moderate-intensity aerobic exercise regimen of 30 minutes, 5 days a week.',
    ],
  },
  {
    id: 'pred-2',
    patientName: 'Clarissa Evans',
    patientAge: 29,
    diseaseType: 'Kidney Stone',
    confidence: 94,
    severity: 'Severe',
    date: '2026-06-23',
    suggestedSpecialist: 'Urology (Dr. Robert Vance)',
    symptomsOrMetrics: {
      'pH Level': 5.2,
      'Urine Specific Gravity': 1.028,
      'Pain Level': 'Severe flank/back pain',
      'Hematuria': 'Yes (visible microscopic blood)',
      'Calcium Concentration': '12.4 mmol/L',
    },
    diagnosisText: 'Highly consistent with active nephrolithiasis (kidney stones), reinforced by severely high calcium concentration, highly acidic urine (pH 5.2), and acute flank pain. Probable stone located in the left ureter.',
    recommendations: [
      'Increase fluid intake immediately (minimum 3.5 liters/day of water).',
      'Consult Dr. Robert Vance immediately for potential shockwave lithotripsy (ESWL) or ureteroscopy.',
      'Limit high-oxalate foods (spinach, nuts, chocolate, tea).',
      'Manage pain using prescribed non-steroidal anti-inflammatory drugs.',
    ],
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    user: 'Admin Staff',
    action: 'Database Synchronization',
    date: '2026-06-25 08:30 AM',
    details: 'Successfully connected Express backend server to the React clinical frontend pipeline.',
    type: 'System',
  },
  {
    id: 'log-2',
    user: 'Dr. Michael Chang',
    action: 'Doctor Portal Login',
    date: '2026-06-25 09:12 AM',
    details: 'Logged into diagnostic terminal from neurology department IP 192.168.12.44.',
    type: 'Login',
  },
  {
    id: 'log-3',
    user: 'AI Core Agent',
    action: 'Model Initialization',
    date: '2026-06-25 09:15 AM',
    details: 'Pre-warmed Gemini-3.5-Flash model with clinical fine-tuning system templates.',
    type: 'Analysis',
  },
  {
    id: 'log-4',
    user: 'John Doe',
    action: 'Appointment Scheduled',
    date: '2026-06-25 10:01 AM',
    details: 'Booked appointment with Dr. Sarah Jenkins (Cardiology) for 2026-06-26.',
    type: 'Appointment',
  },
];

// Presets for AI analysis tools so that users can click and instantly populate correct parameters for realistic simulations.
export const CLINICAL_PRESETS = {
  heart: [
    {
      label: 'Patient A: Stable Normal',
      age: 38,
      bloodPressure: 118,
      cholesterol: 185,
      maxHeartRate: 172,
      chestPain: 'Asymptomatic',
      exerciseAngina: 'No',
    },
    {
      label: 'Patient B: High Cardiovascular Risk',
      age: 62,
      bloodPressure: 155,
      cholesterol: 288,
      maxHeartRate: 142,
      chestPain: 'Typical Angina',
      exerciseAngina: 'Yes',
    },
  ],
  liver: [
    {
      label: 'Normal Liver Profile',
      age: 27,
      bilirubin: 0.8,
      alkPhos: 92,
      alt: 24,
      ast: 28,
      proteins: 7.2,
      albumin: 4.4,
    },
    {
      label: 'Abnormal (Potential Hepatitis / Fatty Liver)',
      age: 51,
      bilirubin: 2.9,
      alkPhos: 285,
      alt: 115,
      ast: 142,
      proteins: 5.9,
      albumin: 2.8,
    },
  ],
  lungs: [
    {
      label: 'Healthy Non-Smoker',
      age: 24,
      smoking: 'Never',
      cough: 'No',
      shortnessOfBreath: 'No',
      chestPain: 'No',
      fatigue: 'None',
    },
    {
      label: 'Chronic Smoker (High Bronchitis/Pneumonia Risk)',
      age: 59,
      smoking: 'Heavy Smoker',
      cough: 'Yes (Chronic)',
      shortnessOfBreath: 'Yes',
      chestPain: 'Yes',
      fatigue: 'Severe',
    },
  ],
  kidney: [
    {
      label: 'Normal Urinary Profile',
      age: 34,
      calcium: 4.2,
      ph: 6.5,
      gravity: 1.015,
      pain: 'None',
      hematuria: 'No',
    },
    {
      label: 'Active Calcium Oxalate Stone Risk',
      age: 46,
      calcium: 11.5,
      ph: 5.1,
      gravity: 1.029,
      pain: 'Severe (Flank Area)',
      hematuria: 'Yes',
    },
  ],
  cancer: [
    {
      label: 'Low Risk Screening',
      age: 31,
      tumorSize: 0,
      familyHistory: 'No',
      lymphNodes: 'Normal',
      weightLoss: 'No',
      fatigue: 'Mild',
    },
    {
      label: 'Oncology Concern (Solid Tumor Scan Required)',
      age: 54,
      tumorSize: 28,
      familyHistory: 'Yes',
      lymphNodes: 'Swollen/Enlarged',
      weightLoss: 'Yes (Unexplained)',
      fatigue: 'Severe',
    },
  ],
  brain: [
    {
      label: 'Normal Brain Profile',
      age: 22,
      headache: 'None',
      seizures: 'No',
      vision: 'Normal',
      cognitive: 'Normal',
      balance: 'Perfect',
    },
    {
      label: 'Neurological Emergency (Scan Immediately)',
      age: 48,
      headache: 'Intense (Morning migraines)',
      seizures: 'Yes',
      vision: 'Blurred',
      cognitive: 'Mild confusion',
      balance: 'Unsteady',
    },
  ],
};

// Realistic clinical images (base64 SVG or curated Unsplash with specific clinical vibes) for scanner presets
export const SCAN_PRESETS = [
  {
    id: 'scan-normal-chest',
    name: 'Normal Chest X-ray',
    modality: 'X-ray',
    organ: 'Lungs',
    url: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?auto=format&fit=crop&q=80&w=400',
    clinicalDescription: 'Standard chest radiograph. Clear costophrenic angles, normal cardiothoracic ratio, clear lung fields with no consolidation or focal opacities.',
  },
  {
    id: 'scan-pneumonia-chest',
    name: 'Pneumonia Chest X-ray',
    modality: 'X-ray',
    organ: 'Lungs',
    url: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&q=80&w=400',
    clinicalDescription: 'Bilateral mid-to-lower zone patchy airspace consolidation. Prominent broncho-vascular markings consistent with clinical viral/bacterial pneumonia.',
  },
  {
    id: 'scan-normal-brain',
    name: 'Healthy Brain MRI',
    modality: 'MRI',
    organ: 'Brain',
    url: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?auto=format&fit=crop&q=80&w=400',
    clinicalDescription: 'Axial T2-weighted MRI scan. Unremarkable sulcal pattern, symmetric ventricles, no midline shift, healthy brain parenchyma with zero tumor indication.',
  },
  {
    id: 'scan-glioma-brain',
    name: 'Glioblastoma Brain MRI',
    modality: 'MRI',
    organ: 'Brain',
    url: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&q=80&w=400',
    clinicalDescription: 'Coronal T1 post-contrast brain MRI. Well-defined space-occupying lesion with ring enhancement in the right temporal lobe, significant vasogenic edema.',
  },
  {
    id: 'scan-stone-kidney',
    name: 'Kidney Stone CT Scan',
    modality: 'CT Scan',
    organ: 'Kidneys',
    url: 'https://images.unsplash.com/photo-1516062423079-7ca13cdc7f5a?auto=format&fit=crop&q=80&w=400',
    clinicalDescription: 'Non-contrast helical CT scan of pelvis. Hyperdense calculus measures 6.5 mm located in the distal left vesicoureteric junction, causing secondary mild hydronephrosis.',
  },
];
